[project]
name = "dr-owl-api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.4",
    "fastapi>=0.116.1",
    "faststream>=0.5.47",
    "ruff>=0.12.3",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.35.0",
]
