"""add null to 'processed text'

Revision ID: 48125cb10225
Revises: 57d6351b4f8a
Create Date: 2025-07-24 13:08:29.321800

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "48125cb10225"
down_revision: Union[str, Sequence[str], None] = "57d6351b4f8a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "processed_text", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "documents", "processed_text", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
